version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: miatapodium-server-postgres
    restart: always
    environment:
      POSTGRES_USER: miatapodium
      POSTGRES_PASSWORD: miatapodium
      POSTGRES_DB: miatapodium
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: